version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    hostname: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "logistics-events:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  auth:
      image: amitmahajan/logistics-auth:0.1
      ports:
        - "8090:8090"
      environment:
        DB_AUTH_IP: host.docker.internal
  orders:
    image: sunday/order-api:1.0
    ports:
      - "9001:9001"
    environment:
      DB_HOST_IP: host.docker.internal
      KAFKA_INFRA_HOST_IP: kafka
      AUTH_SERVER_URL: auth
  stock:
    image: sunday/stock-api:1.0
    ports:
      - "9004:9004"
    environment:
      DB_HOST_IP: host.docker.internal
      KAFKA_INFRA_HOST_IP: kafka
      AUTH_SERVER_URL: auth
  shipment:
    image: sunday/shipment-api:1.0
    ports:
      - "9002:9002"
    environment:
      DB_HOST_IP: host.docker.internal
      KAFKA_INFRA_HOST_IP: kafka
      AUTH_SERVER_URL: auth
  query:
    image: sunday/query-api:1.3
    ports:
      - "9003:9003"
    environment:
      DB_HOST_IP: host.docker.internal
      KAFKA_INFRA_HOST_IP: kafka
      AUTH_SERVER_URL: auth
  gateway:
    image: amitmahajan/gateway:2.2
    ports:
      - "9090:9090"
    environment:
      ORDER_SERVER_URL: orders
      STOCK_SERVER_URL: stock
      AUTH_SERVER_URL: auth
      SHIPMENT_SERVER_URL: shipment
      QUERY_SERVER_URL: query